### PR TITLE
[#247] Hide inert address-book button

### LINKED ISSUE #247: Hide Address book button
### Describe the issue
In the profile screen, an inert button to open the address book is present.

#### If so, please list the steps to reproduce below:
1. From the app's home screen, tap the profile button

### Expected behavior
Address book button should be hidden

### Actual behavior + errors
Address book button is visible

### Any extra information that might be useful in the debugging process.
We hope to add address book as a feature in the future, so we can just hide the button instead of deleting it.  Hiding it for now ensures that users don't see non-functional button in the UI.

### PR DESCRIPTION
**Pull request by luckytokidoki**
fix #247

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Manual tests: Did you update the [manual tests](../blob/main/docs/testing/manual_testing) as appropriate? _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
- [x] Code coverage: Did you check the code coverage report for the automated tests?  _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed._
- [ ] Documentation: Did you update documentation as appropriate? (e.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes?
- [x] Screenshots: Did you provide before and after UI screenshots in the description of this pull request?  _This is only applicable for changes that modify the UI._
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
secant_issue_247_s

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after your changes and when possible, leave it in a better place._
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

File: ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/view/ProfileView.kt [hunk 1]
```diff
@@ -108,7 +108,8 @@ private fun ProfileContents(
     onAddressBook: () -> Unit,
     onSettings: () -> Unit,
     onCoinholderVote: () -> Unit,
-    onSupport: () -> Unit
+    onSupport: () -> Unit,
+    isHidden: Boolean = false
```
Comment (ccjernigan) [inline ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/view/ProfileView.kt:112]: I'd like to suggest a more descriptive variable name, to make the public API more clear about what will be hidden.

```suggestion
    isAddressBookEnabled: Boolean = false
```

**Review by ccjernigan — CHANGES_REQUESTED** [review]
Thank you for the pull request.

In addition to the inline suggestion, can you also please run the automated tests for ui-lib?  There should be a run configuration for Android Studio, or `./gradlew ui-lib:connectedCheck` from the command line.  There will be a failing test case that needs to be resolved.

We are working to have the tests run on GitHub Actions, although that isn't set up yet so running tests locally is the best option for now.

File: ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/view/ProfileView.kt (hunk 1 above)
Comment (luckytokidoki) [reply ui-lib/src/main/java/cash/z/ecc/ui/screen/profile/view/ProfileView.kt]: Thanks a lot for the suggestion. I have changed the var name.

I have also addressed the failed connectedDevice test by adding `@ignore` annotation to the relevant test.

Cheers.

**Review by ccjernigan — APPROVED** [review]
